name: appcheck
description: Flutter plugin that allows you to check if an app is installed/enabled, launch an app and get the list of installed apps.
version: 1.0.6
homepage: https://github.com/Yash-Garg/appcheck

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.yashgarg.appcheck
        pluginClass: AppcheckPlugin
      ios:
        pluginClass: AppcheckPlugin
